language: node_js
sudo: false

node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

cache:
  directories:
    - node_modules

after_script:
- npm run coverage

notifications:
  email:
    on_success: never
    on_failure: always
